### ISSUE TITLE
Access denied in windows 11

### ISSUE THREAD

**Issue by cdprf** [jreisinger/checkip#33]
i want to update version in my pc.

i download it with wget(windows) then extract it in previously directory.

```
PS C:\Portables\Tools> .\checkip.exe
Program 'checkip.exe' failed to run: Access is deniedAt line:1 char:1
+ .\checkip.exe
+ ~~~~~~~~~~~~~.
At line:1 char:1
+ .\checkip.exe
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

```

i search a clue about wich file are denies but no luck.

i have .checkip.yaml in same directory also i copied it in to my user path.  c:\users\yunus\.checkip.yaml

do you have any idea how can i run it. ?

**Comment by jreisinger** [comment]
Hi @cdprf. I don't have access to Windows (I use Linux + Mac) but a quick googling gave me this https://stackoverflow.com/questions/69671055/program-a-exe-failed-to-run-access-is-deniedat-line1-char1. Are you maybe running some antivirus program?

**Comment by cdprf** [comment]
thanks for the info,

yes i guess its related with some kind of security issue, i am using Windows defender,  that folder was in exlusion list.

somehow its blocking. even i disable av i still cannot run.


i installed Mcafee , then scan my pc, then remove it. also tryed to resetting Windows defender settings completely but no luck atm.

current situaition of my console like this.

`PS C:\Users\yunus> checkip.exe 172.64.146.***
C:\Portables\Tools\checkip.exe: Ping: socket: The requested protocol has not been configured into the system, or no implementation for it exists.
C:\Portables\Tools\checkip.exe: mkdir C:\Users\yunus\.checkip: Cannot create a file when that file already exists.
C:\Portables\Tools\checkip.exe: mkdir C:\Users\yunus\.checkip: Cannot create a file when that file already exists.
C:\Portables\Tools\checkip.exe: mkdir C:\Users\yunus\.checkip: Cannot create a file when that file already exists.
C:\Portables\Tools\checkip.exe: Tls: remote error: tls: handshake failure
db-ip.com       Toronto, Canada
iptoasn.com     CLOUDFLARENET
malicious       0% (0/2) ✅`

**Comment by cdprf** [comment]
still not working, but i found the problem.

microsoft's new 365 defender stuf has a "Attack surface reduction" and its blocking powershell windows, then block checkip.exe too.
now i am trying to leave that microsoft 365 thingy.
https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-protection-windows-10#attack-surface-reduction-rules

thanks for the help.
